project:
  type: website
  output-dir: docs

website:
  title: "Madeline Marco Scanlon"
  navbar:
    background: "#003594"
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - cv.qmd
      - teaching.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

editor: visual

